package com.kapasiya.sharefair.work

import android.content.Context
import androidx.work.CoroutineWorker
import androidx.work.WorkerParameters
import com.google.firebase.firestore.FirebaseFirestore
import com.kapasiya.sharefair.model.Bill
import com.kapasiya.sharefair.model.RecurringBill
import kotlinx.coroutines.tasks.await
import java.util.Calendar

class RecurringBillWorker(context: Context, params: WorkerParameters) : CoroutineWorker(context, params) {
    override suspend fun doWork(): Result {
        val db = FirebaseFirestore.getInstance()
        
        try {
            // Find all recurring bill templates from all groups
            // In a real app, this might be a separate collection or a flag on groups
            val groups = db.collection("groups").get().await()
            
            for (groupDoc in groups.documents) {
                val groupId = groupDoc.id
                val recurringBills = db.collection("groups").document(groupId)
                    .collection("recurring_bills").get().await()
                    
                for (rbDoc in recurringBills.documents) {
                    val rb = rbDoc.toObject(RecurringBill::class.java) ?: continue
                    
                    if (shouldGenerateNow(rb)) {
                        generateBillFromTemplate(groupId, rb, db)
                    }
                }
            }
            
            return Result.success()
        } catch (e: Exception) {
            return Result.retry()
        }
    }

    private fun shouldGenerateNow(rb: RecurringBill): Boolean {
        val last = rb.lastGeneratedTimestamp
        val now = System.currentTimeMillis()
        val interval = when (rb.frequency) {
            "WEEKLY" -> 7L * 24 * 60 * 60 * 1000
            "MONTHLY" -> {
                val cal = Calendar.getInstance()
                cal.timeInMillis = last
                cal.add(Calendar.MONTH, 1)
                return now >= cal.timeInMillis
            }
            else -> 0L
        }
        return now - last >= interval
    }

    private suspend fun generateBillFromTemplate(groupId: String, rb: RecurringBill, db: FirebaseFirestore) {
        val bill = Bill(
            id = "", // Generated by Firestore
            title = rb.title + " (Auto)",
            amount = rb.amount,
            payerId = rb.payerId,
            splitType = rb.splitType,
            participantsMap = rb.participantsMap,
            timestamp = System.currentTimeMillis()
        )
        
        // Add to bills collection
        val billRef = db.collection("groups").document(groupId).collection("bills").document()
        db.collection("groups").document(groupId).collection("bills")
            .document(billRef.id).set(bill.copy(id = billRef.id)).await()
            
        // Update template's lastGeneratedTimestamp
        db.collection("groups").document(groupId).collection("recurring_bills")
            .document(rb.id).update("lastGeneratedTimestamp", System.currentTimeMillis()).await()
    }
}
